dist: trusty
language: php

php:
  - 7.1

env:
  global:
    - setup=basic

sudo: required

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - redis-server

addons:
  chrome: stable

before_install:
  - nvm install node

install:
  - cp .env.testing .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - yarn install
  - yarn run prod

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk