sudo: required
language: php
dist: trusty

cache:
  yarn: true
  directories:
    - node_modules

php:
  - 7.1

before_install:
  - nvm install node

install:
  - travis_retry composer install --no-interaction
  - yarn install
  - yarn run prod

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - cp .env.testing .env
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk